config ip ok
Signed-off-by: Lindell Xu <lxu@vetronicsltd.com.cn>

diff --git a/ux400-mod-test b/ux400-mod-test
--- a/ux400-mod-test
+++ b/ux400-mod-test
@@ -15,6 +15,7 @@ USB2=3
 USB3=4
 USB4=5
 USB5=6
+USB0_5=(1 2 3 4 5 6)
 
 udport=8030
 serverport=8031
@@ -69,7 +70,7 @@ function modretry()
                 /sbin/ux400cset
                 sleep 20
                 mtype $1
-                machine="$?"
+                local machine="$?"
                 if [ "$machine" == "$UNKNOW" ]; then
                         /usr/bin/ux400gpio $1 0
                         /sbin/ux400cset
@@ -122,111 +123,46 @@ function modconfig()
         return 0
 }
 
+isusb () {
+	local var
+	for var in "${@:2}"; do
+		[[ "$var" == "$1" ]] && return 0
+	done
+	return 1
+}
+
 
 function configip()
 {
         mdevcheck $1
-        usbdev="$?"
-	if [ "$usbdev" == "$USB0" ]; then
-		modconfig usb0 192.168.250.2 128.0.0.2 255.255.255.252 128.0.0.1
+        local usbdev="$?"
+
+	isusb "$usbdev" "${USB0_5[@]}"
+	if [ $? -eq 0 ]; then
+		local usbx=`expr $usbdev - 1`
+		local host=`expr $usbx \* 4 + 1`
+		local sub=`expr $usbx \* 4 + 2`
+		local x86_ip="128.0.0.$host"
+		local arm_ip="128.0.0.$sub"
+		local usb_eth="usb$usbx"
+		echo "$1: $usb_eth, x86_ip=$x86_ip, arm_ip=$arm_ip" > ${display_dev}
+		modconfig $usb_eth 192.168.250.2 $arm_ip 255.255.255.252 $x86_ip
 		if [ $? -ne 0 ]; then
 			/usr/bin/ux400gpio $1 0
 			sleep ${DELAY_MHALT}
 			/usr/bin/ux400gpio $1 1
 			sleep ${DELAY_SUBBOARD}
-			modconfig usb0 192.168.250.2 128.0.0.2 255.255.255.252 128.0.0.1
+			modconfig $usb_eth 192.168.250.2 $arm_ip 255.255.255.252 $x86_ip
 			if [ $? -ne 0 ]; then
 				/sbin/ux400cset
-				ifconfig usb0 down
-				echo -e "Can't connect to usb0\r" > ${display_dev}
-				sleep 60
-				return 3
+				ifconfig $usb_eth down
+				echo -e "Can't connect to $usb_eth\r" > ${display_dev}
 			fi
 		fi
-        elif [ "$usbdev" == "$USB1" ]; then
-                modconfig usb1 192.168.250.2 128.0.0.6 255.255.255.252 128.0.0.5
-		if [ $? -ne 0 ]; then
-                        /usr/bin/ux400gpio $1 0
-                        sleep ${DELAY_MHALT}
-                        /usr/bin/ux400gpio $1 1
-                        sleep ${DELAY_SUBBOARD}
-			modconfig usb1 192.168.250.2 128.0.0.6 255.255.255.252 128.0.0.5
-			if [ $? -ne 0 ]; then
-				ifconfig usb1 down
-				echo -e "Can't connect to usb1\r" > ${display_dev}
-                                sleep 60
-				return 3
-			fi
-		fi
-        elif [ "$usbdev" == "$USB2" ]; then
-                modconfig usb2 192.168.250.2 128.0.0.10 255.255.255.252 128.0.0.9
-		if [ $? -ne 0 ]; then
-                        /usr/bin/ux400gpio $1 0
-                        sleep ${DELAY_MHALT}
-                        /usr/bin/ux400gpio $1 1
-                        sleep ${DELAY_SUBBOARD}
-			modconfig usb2 192.168.250.2 128.0.0.10 255.255.255.252 128.0.0.9
-                        if [ $? -ne 0 ]; then
-				/sbin/ux400cset
-				ifconfig usb2 down
-                                echo -e "Can't connect to usb2\r" > ${display_dev}
-                                sleep 60
-                                return 3
-                        fi
-		fi
-        elif [ "$usbdev" == "$USB3" ]; then
-                modconfig usb3 192.168.250.2 128.0.0.14 255.255.255.252 128.0.0.13
-		if [ $? -ne 0 ]; then
-                        /usr/bin/ux400gpio $1 0
-                        sleep ${DELAY_MHALT}
-                        /usr/bin/ux400gpio $1 1
-                        sleep ${DELAY_SUBBOARD}
-			modconfig usb3 192.168.250.2 128.0.0.14 255.255.255.252 128.0.0.13
-                        if [ $? -ne 0 ]; then
-				/sbin/ux400cset
-				ifconfig usb3 down
-                                echo -e "Can't connect to usb3\r" > ${display_dev}
-                                sleep 60
-                                return 3
-                        fi
-		fi
-        elif [ "$usbdev" == "$USB4" ]; then
-                modconfig usb4 192.168.250.2 128.0.0.18 255.255.255.252 128.0.0.17
-		if [ $? -ne 0 ]; then
-                        /usr/bin/ux400gpio $1 0
-                        sleep ${DELAY_MHALT}
-                        /usr/bin/ux400gpio $1 1
-                        sleep ${DELAY_SUBBOARD}
-			modconfig usb4 192.168.250.2 128.0.0.18 255.255.255.252 128.0.0.17
-                        if [ $? -ne 0 ]; then
-				/sbin/ux400cset
-				ifconfig usb4 down
-                                echo -e "Can't connect to usb4\r" > ${display_dev}
-                                sleep 60
-                                return 3
-                        fi
-		fi
-        elif [ "$usbdev" == "$USB5" ]; then
-                modconfig usb5 192.168.250.2 128.0.0.22 255.255.255.252 128.0.0.21
-		if [ $? -ne 0 ]; then
-                        /usr/bin/ux400gpio $1 0
-                        sleep ${DELAY_MHALT}
-                        /usr/bin/ux400gpio $1 1
-                        sleep ${DELAY_SUBBOARD}
-			modconfig usb5 192.168.250.2 128.0.0.22 255.255.255.252 128.0.0.21
-                        if [ $? -ne 0 ]; then
-				/sbin/ux400cset
-				ifconfig usb5 down
-                                echo -e "Can't connect to usb5\r" > ${display_dev}
-                                sleep 60
-                                return 3
-                        fi
-		fi
-	else
-#		echo -e "Unsupport USB device" > ${display_dev}
-		return 0
-        fi
 
+	else
+		echo -e "$1: Unsupport USB device" > ${display_dev}
+	fi
 }
 
 #slots
@@ -235,7 +171,7 @@ function mupgrade()
 
 	/sbin/ux400cset
 	bucheck $1
-	update="$?"
+	local update="$?"
 	echo -ne "    \r" > ${display_dev}
 
 
@@ -253,7 +189,10 @@ function mupgrade()
 	fi
 	
 	mtype $1
-	machine="$?"
+	local machine="$?"
+	local imagename=""
+	local machinename=""
+	local boardname=""
 
 	rm -rf /resv/v400/ux400-module-sd.tar.gz
 
@@ -381,7 +320,7 @@ function mupgrade()
 		return 3
 	fi
 
-	echo -e $imagename
+	echo "$1: $machine, $imagename, $machinename, $boardname" > ${display_dev}
 
         cp -rf /usr/bin/mdarms /resv/v400/
         cp -rf /usr/bin/kill-mods /resv/v400/
@@ -394,22 +333,31 @@ function mupgrade()
 	
 	/sbin/ux400cset
 	mdevcheck $1
-	usbdev="$?"
-	locate=$1
+	local usbdev="$?"
+	local locate=$1
 	/sbin/ux400cset
 	ifconfig eth0 up
 
-	if [ "$usbdev" == "$USB0" ]; then
+	isusb "$usbdev" "${USB0_5[@]}"
+	if [ $? -eq 0 ]; then
+		local usbx=`expr $usbdev - 1`
+		local host=`expr $usbx \* 4 + 1`
+		local sub=`expr $usbx \* 4 + 2`
+		local x86_ip="128.0.0.$host"
+		local arm_ip="128.0.0.$sub"
+		local usb_eth="usb$usbx"
+		echo "$1: usb$usbx, x86_ip=$x86_ip, arm_ip=$arm_ip" > ${display_dev}
+
 		rm -rf /resv/v400/$1fup.log
-		ping 128.0.0.2 -c 1
+		ping $arm_ip -c 1
 		if [ $? -ne 0 ]; then
-			ifconfig usb0 192.168.250.3  up
-			modconfig usb0 192.168.250.2 128.0.0.2 255.255.255.252 128.0.0.1
+			ifconfig $usb_eth 192.168.250.3  up
+			modconfig $usb_eth 192.168.250.2 $arm_ip 255.255.255.252 $x86_ip
 		fi
 
-		/usr/bin/modud 128.0.0.2 128.0.0.1 $udport
+		/usr/bin/modud $arm_ip $x86_ip $udport
 		sleep 5
-		/usr/bin/client 128.0.0.2 $udport 128.0.0.1 $imagename $boardname /resv/v400/$1fup.log $locate > ${display_dev}
+		/usr/bin/client $arm_ip $udport $x86_ip $imagename $boardname /resv/v400/$1fup.log $locate > ${display_dev}
 		grep -r "SUCCESS" /resv/v400/$1fup.log
 	  	if [ $? -ne 0 ]; then
 			echo -n "The " > ${display_dev}
@@ -424,7 +372,7 @@ function mupgrade()
 				echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
 				rm -rf /resv/v400/$1sdup.log
 	                        sleep ${DELAY_SD}
-				/usr/bin/client 128.0.0.2 $udport 128.0.0.1 ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev}
+				/usr/bin/client $arm_ip $udport $x86_ip ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev}
                 	        if [ $? -ne 0 ]; then
 					/usr/bin/sdupfail > ${display_dev}
 					sleep 1
@@ -438,226 +386,12 @@ function mupgrade()
 			echo -n " module in slot " > ${display_dev}
 			echo -n "$1" > ${display_dev}
 			echo -e " upgrade success\r" > ${display_dev}
-			/usr/bin/modoff 128.0.0.2
-			/sbin/ux400cset
-			return 1
-	  	fi
-	elif [ "$usbdev" == "$USB1" ]; then
-		rm -rf /resv/v400/$1fup.log
-                ping 128.0.0.6 -c 1
-                if [ $? -ne 0 ]; then
-			ifconfig usb1 192.168.250.3 up
-			modconfig usb1 192.168.250.2 128.0.0.6 255.255.255.252 128.0.0.5
-                fi
-
-		/usr/bin/modud 128.0.0.6 128.0.0.5 $udport
-		sleep 5
-		/usr/bin/client 128.0.0.6 $udport 128.0.0.5 $imagename $boardname /resv/v400/$1fup.log $locate > ${display_dev}
-		grep -r "SUCCESS" /resv/v400/$1fup.log
-	  	if [ $? -ne 0 ]; then
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
-			return 3
-			/sbin/ux400cset
-	  	else
-		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
-                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
-				rm -rf /resv/v400/$1sdup.log
-                                sleep ${DELAY_SD}
-                                /usr/bin/client 128.0.0.6 $udport 128.0.0.5 ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev}
-                                if [ $? -ne 0 ]; then
-					/usr/bin/sdupfail > ${display_dev}
-					sleep 1
-					halt
-					return 0
-				fi
-                        fi
-
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade success\r" > ${display_dev}
-			/sbin/ux400cset
-			/usr/bin/modoff 128.0.0.6
-			return 1
-	  	fi
-	elif [ "$usbdev" == "$USB2" ]; then
-		rm -rf /resv/v400/$1fup.log
-                ping 128.0.0.10 -c 1
-                if [ $? -ne 0 ]; then
-			ifconfig usb2 192.168.250.3 up
-			modconfig usb2 192.168.250.2 128.0.0.10 255.255.255.252 128.0.0.9
-                fi
-
-		/usr/bin/modud 128.0.0.10 128.0.0.9 $udport
-		sleep 5
-		/usr/bin/client 128.0.0.10 $udport 128.0.0.9 $imagename $boardname /resv/v400/$1fup.log $locate > ${display_dev}
-		grep -r "SUCCESS" /resv/v400/$1fup.log
-	  	if [ $? -ne 0 ]; then
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
-			/sbin/ux400cset
-			return 3
-	  	else
-		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
-                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
-				rm -rf /resv/v400/$1sdup.log
-                                sleep ${DELAY_SD}
-                                /usr/bin/client 128.0.0.10 $udport 128.0.0.9 ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev}
-                                if [ $? -ne 0 ]; then
-					/usr/bin/sdupfail > ${display_dev}
-					sleep 1
-					halt
-					return 0
-                                fi
-                        fi
-
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade success\r" > ${display_dev}
-			/usr/bin/modoff 128.0.0.10
-			/sbin/ux400cset
-			return 1
-	  	fi
-	elif [ "$usbdev" == "$USB3" ]; then
-		rm -rf /resv/v400/$1fup.log
-                ping 128.0.0.14 -c 1
-                if [ $? -ne 0 ]; then
-			ifconfig usb3 192.168.250.3 up
-			modconfig usb3 192.168.250.2 128.0.0.14 255.255.255.252 128.0.0.13
-                fi
-
-		/usr/bin/modud 128.0.0.14 128.0.0.13 $udport
-		sleep 5
-		/usr/bin/client 128.0.0.14 $udport 128.0.0.13 $imagename $boardname /resv/v400/$1fup.log $locate > ${display_dev}
-		grep -r "SUCCESS" /resv/v400/$1fup.log
-		if [ $? -ne 0 ]; then
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
-			/sbin/ux400cset
-			return 3
-	  	else
-		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
-                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
-				rm -rf /resv/v400/$1sdup.log
-                                sleep ${DELAY_SD}
-                                /usr/bin/client 128.0.0.14 $udport 128.0.0.13 ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev}
-                                if [ $? -ne 0 ]; then
-					/usr/bin/sdupfail > ${display_dev}
-					sleep 1
-					halt
-					return 0
-				fi
-                        fi
-
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade success\r" > ${display_dev}
-			/usr/bin/modoff 128.0.0.14
-			/sbin/ux400cset
-			return 1
-	  	fi
-	elif [ "$usbdev" == "$USB4" ]; then
-		rm -rf /resv/v400/$1fup.log
-                ping 128.0.0.18 -c 1
-                if [ $? -ne 0 ]; then
-			ifconfig usb4 192.168.250.3 up
-			modconfig usb4 192.168.250.2 128.0.0.18 255.255.255.252 128.0.0.17
-                fi
-
-		/usr/bin/modud 128.0.0.18 128.0.0.17 $udport
-		sleep 5
-		/usr/bin/client 128.0.0.18 $udport 128.0.0.17 $imagename $bardname /resv/v400/$1fup.log $locate > ${display_dev}
-		grep -r "SUCCESS" /resv/v400/$1fup.log
-	  	if [ $? -ne 0 ]; then
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
-			/sbin/ux400cset
-			return 3
-	  	else
-		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
-				rm -rf /resv/v400/$1sdup.log
-                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
-                                sleep ${DELAY_SD}
-                                /usr/bin/client 128.0.0.18 $udport 128.0.0.17 ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev}
-                                if [ $? -ne 0 ]; then
-					/usr/bin/sdupfail > ${display_dev}
-					sleep 1
-					halt
-					return 0
-                                fi
-                        fi
-
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade success\r" > ${display_dev}
-			/usr/bin/modoff 128.0.0.18
-			/sbin/ux400cset
-			return 1
-	  	fi
-	elif [ "$usbdev" == "$USB5" ]; then
-		rm -rf /resv/v400/$1fup.log
-                ping 128.0.0.22 -c 1
-                if [ $? -ne 0 ]; then
-			ifconfig usb5 192.168.250.3 up
-			modconfig usb5 192.168.250.2 128.0.0.22 255.255.255.252 128.0.0.21
-                fi
-		/usr/bin/modud 128.0.0.22 128.0.0.21 $udport
-		sleep 5
-		/usr/bin/client 128.0.0.22 $udport 128.0.0.21 $imagename $boardname /resv/v400/$1fup.log $locate > ${display_dev}
-		grep -r "SUCCESS" /resv/v400/$1fup.log
-	  	if [ $? -ne 0 ]; then
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade failed, please try again, if you always see this, please contact customer service\r" > ${display_dev}
-			/sbin/ux400cset
-			return 3
-	  	else
-		        if [ -f /usr/local/$boardname/share/ux400-module-sd.tar.gz ]; then
-                                echo "Test Module $1: Flash upgrade done, find module SD card image, upgrade SD card." > ${display_dev}
-				rm -rf /resv/v400/$1sdup.log
-                                sleep ${DELAY_SD}
-                                /usr/bin/client 128.0.0.22 $udport 128.0.0.21 ux400-module-sd.tar.gz $boardname /resv/v400/$1sdup.log $locate > ${display_dev} 
-                                if [ $? -ne 0 ]; then
-					/usr/bin/sdupfail > ${display_dev}
-					sleep 1
-					halt
-					return 0
-                                fi
-                        fi
-
-			echo -n "The " > ${display_dev}
-			echo -n $machinename > ${display_dev}
-			echo -n " module in slot " > ${display_dev}
-			echo -n "$1" > ${display_dev}
-			echo -e " upgrade success\r" > ${display_dev}
-			/usr/bin/modoff 128.0.0.22
+			/usr/bin/modoff $arm_ip
 			/sbin/ux400cset
 			return 1
 	  	fi
 	else
-		echo "Unsupport USB device"
+		echo -e "Unsupport USB device" > ${display_dev}
 	fi
 }
 
@@ -665,7 +399,7 @@ function mupgrade()
 function multiup()
 {
 	mtype $1
-	machine="$?"
+	local machine="$?"
 	if [ "$machine" == "$UNKNOW" ]; then
 	        echo -e "Can't find module board at slot $1\r"
 
